run:
  concurrency: 4
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  go: '1.23'

issues:
  exclude-rules:

    - path: common/turbotunnel/queuepacketconn.go
      linters:
        - staticcheck
      text: "SA6002: argument should be pointer-like to avoid allocations"

    - path: client/lib/
      linters:
        - gosec
      text: "G404: Use of weak random number generator"

    - path: common/turbotunnel/redialpacketconn.go
      linters:
        - errcheck

    - path: test.go
      linters:
        - errcheck
        - gosec
        - ineffassign
        - staticcheck

    - path: broker/
      linters:
        - errcheck
      text: "Error return value of"

    - path: server/
      linters:
        - errcheck
      text: "Error return value of"
