version: "2"

run:
  concurrency: 4
  tests: true
  allow-parallel-runners: true
  go: '1.24'

linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:

      - linters:
          - staticcheck
        path: common/turbotunnel/queuepacketconn.go
        text: 'SA6002: argument should be pointer-like to avoid allocations'

      - linters:
          - gosec
        path: client/lib/
        text: 'G404: Use of weak random number generator'

      - linters:
          - errcheck
        path: common/turbotunnel/redialpacketconn.go

      - linters:
          - errcheck
          - gosec
          - ineffassign
          - staticcheck
        path: test.go

      - linters:
          - errcheck
        path: broker/
        text: Error return value of

      - linters:
          - errcheck
        path: server/
        text: Error return value of

    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
