#!/bin/sh

# copied from debhelper
# https://sources.debian.org/src/debhelper/14.3/autoscripts/postinst-systemd-enable
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled snowflake-proxy.service; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable snowflake-proxy.service >/dev/null || true
		deb-systemd-invoke restart snowflake-proxy.service >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state snowflake-proxy.service >/dev/null || true
	fi
fi
