name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    strategy:
      matrix:
        go-version: [ '1.21', '1.22' ]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: false

    - name: Build
      run: go build -v ./...

    - name: Test
      run: CGO_ENABLED=1 go test -v -race ./... -covermode=atomic -coverprofile=coverage.out

    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.out
        flags: unittests
        verbose: true

    - name: GoLang CI Lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        only-new-issues: true
        skip-pkg-cache: true
        skip-build-cache: true
        args: --timeout=5m
